@host = http://localhost:3000

### 1) login et capture token
# @name loginUser
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user1@42.fr",
  "password": "Abc12345!"
}
### 1.1) assignation du token
@token = {{loginUser.response.body.token}}

### 2) Tester le leaderboard
GET {{host}}/api/user/leaderboard
Authorization: Bearer {{token}}