services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node:
    image: node:24
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 5001:5001
    env_file:
      - .env
    command: bash -c "npm install fastify && npm install pg && npm install bcrypt && npm install nodemon && npx nodemon ./backend/server.js && npm start"

volumes:
  pgdata:
