services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 30

  node:
    build: .
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # run: migrate => start (aucun npm install au runtime)
    command: >
      sh -lc "
      cd backend &&
      node scripts/migrate.js &&
      node src/server.js
      "

volumes:
  pgdata:
