services:
  vault:
    image: hashicorp/vault:1.15
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://vault:8200
    ports:
      - "8200:8200"
    volumes:
      - ./scripts/init-vault.sh:/init-vault.sh
    command: vault server -dev -dev-root-token-id=myroot
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:${POSTGRES_VERSION:-14}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: ${POSTGRES_DB:-db_transcendence}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vault-init:
    image: hashicorp/vault:1.15
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://172.18.0.2:8200
      VAULT_TOKEN: myroot
    volumes:
      - ./scripts/init-vault.sh:/init-vault.sh
    command: ["/bin/sh", "/init-vault.sh"]
    profiles:
      - init

  node:
    image: node:24
    working_dir: /home/sgoinfre
    environment:
      - NODE_ENV=dev
      - HTTPS_PORT=5001
    volumes:
      - ./:/home/sgoinfre
      - ./ssl:/home/sgoinfre/ssl:ro  # Monter les certificats SSL
    ports:
      - "5001:5001"
    env_file:
      - .env
    command: bash -c "npm install fastify@5 && npm install pg && npm install dotenv && npm install bcrypt && npm install nodemon && npm install @fastify/jwt && npm install @fastify/cookie && npm install @fastify/cors && npm install nodemailer && npm install @fastify/multipart && npm install @fastify/static && npx nodemon ./backend/src/server-https.js"
    depends_on:
      - db
      - vault

  frontend:
    image: node:24
    working_dir: /home/node/app/frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - ./ssl:/home/node/app/ssl:ro  # Monter les certificats SSL
    ports:
      - "5173:5173"
    depends_on:
      - node
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  pgdata:
