@host = http://localhost:3000

### 0) Créer l'utilisateur si besoin
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user1@42.fr",
  "password": "Abc12345!"
}

### 1) login pour récupérer le token
# @name loginUser
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user1@42.fr",
  "password": "Abc12345!"
}

### 2) Récupérer les statistiques utilisateur
GET {{host}}/api/user/statistics
Authorization: Bearer {{loginUser.response.body.token}}