@baseUrl = http://localhost:5001/api

### 0) login pour récupérer le token
# @name loginUser
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "user1@42.fr",
  "password": "Abc12345!"
}

### 0.1) auth header dérivé du login
@auth = Bearer {{loginUser.response.body.token}}

### 401 sans JWT
GET {{baseUrl}}/leaderboard

### 200 leaderboard
GET {{baseUrl}}/leaderboard?limit=5&offset=0
Authorization: {{auth}}

### 200 stats
GET {{baseUrl}}/statistics
Authorization: {{auth}}

### 201 demande d’ami
POST {{baseUrl}}/friends
Authorization: {{auth}}
Content-Type: application/json

{
  "addresseeId": 2
}

### 200 acceptation d’ami
POST {{baseUrl}}/friends/accept
Authorization: {{auth}}
Content-Type: application/json

{
  "requesterId": 1
}

### 200 settings
GET {{baseUrl}}/settings
Authorization: {{auth}}

### 200 logout
POST {{baseUrl}}/logout
Authorization: {{auth}}
